---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 22519.
--- DateTime: 2025/11/4 16:53
---
if(redis.call('get',KEYS[1])==ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0